name: Build and Test Android App

on:
  push:
    branches: [ main, rollback-working ]
  pull_request:
    branches: [ main, rollback-working  ]
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build
        env:
         GRADLE_OPTS: -Xmx2048m -Dfile.encoding=UTF-8
      - name: Run Tests
        run: ./gradlew test

      - name: Run unit test
        run: ./gradlew clean testDebug
